### ISSUE TITLE
Attempting public release to App Store

### ISSUE THREAD

**Issue by askosh** [askosh/ivory#31]
In order to attempt a public release to the App Store, the following need to be completed:

- [ ] Basic profile view needs to be finished (#28)
- [ ] Basic toot actions need to be finished (#4, #5, #6)
- [ ] Ability to go to your own profile from home view (#30)

**Comment by askosh** [comment]
To anyone reading this; I know this does not include many things that one would think are obviously needed, such as notifications and other timelines, but once the above is done, it's complete enough to be used for the most basic of Matsodon-ing, and thus in my book is a 1.0.

**Comment by askosh** [comment]
I submitted the app for public release of App Store. Will wait to hear back.

**Comment by askosh** [comment]
And we got rejected, having to implement the following precautions:

- [ ] #44 Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users
- [ ] #45 A method for filtering objectionable content
- [ ] #46 A mechanism for users to flag objectionable content
- [ ] #47 A mechanism for users to block abusive users
- The developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content

The last bit I'm not sure on how to achieve, given I don't control the instances users use, but perhaps if I implement the rest they will me through.

**Comment by askosh** [comment]
Alright, I've done all I can (I hope). Will attempt to publish it again at one point.
